name: thirdweb

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_contract:
    runs-on: ubuntu-latest
    outputs:
      # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
      # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
      deploy_output: ${{ steps.deploy.outputs.stdout }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Deploy
        id: deploy
        if: github.event_name == 'push' || github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          echo "DEPLOY=$(npx thirdweb deploy --ci --key "$THIRDWEB_SECRET" | grep -Eo "$THIRDWEB_REGEX" | grep -Eo 'http.+')" >> $GITHUB_ENV
        env:
          THIRDWEB_SECRET: ${{ secrets.ThirdwebSecret }}
          THIRDWEB_REGEX: 'Open this link to deploy your contracts: http.+'
      - name: Set Deloy Link to Output
        run: |
          echo "deploy_url: $DEPLOY"
          echo "stdout=$DEPLOY" >> "$GITHUB_OUTPUT"

  comment_on_commit:
    runs-on: ubuntu-latest
    needs: [deploy_contract]
    if: github.event_name == 'push'
    steps:
      - name: Comment on commit (deploy)
        uses: peter-evans/commit-comment@v2
        if: ${{ needs.deploy_contract.outputs.deploy_output != '' }}
        with:
          body: |
            Contract compiled, deploy using ${{ needs.deploy_contract.outputs.deploy_output }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
